Style Code of Conduct page, update error svg
code-312/Voma pull request #140
Opened 2024-04-27 20:18 UTC by mhyneman8

Updated copy to match figma

2024-04-27 23:49 UTC, daleinen7 requested changes
This looks really good. The only two things I'd adjust is the use of pixels for sizing and then the two headings that are still using MUI. 

I know the `<p>` font is using Roboto, and ideally we'd change that but also I think eventually we'd probably want to go through and unify the type system overall so it's easier to apply so I'll let @raindogg weigh in on how important it is to update the paragraph font at this point.

Otherwise this looks good to me!

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +    height: 60px;
Let's use rem here.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +    padding: 15px;
Let's use rem here.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +        <Typography variant="h6" my={1}>
See above note re: the MUI heading styles.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +          sx={{ display: 'inline-block', marginLeft: '10px', verticalAlign: 'top' }}
Let's use rem here.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +            maxHeight: '600px',
Let's use rem here.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +            padding: '24px',
Let's use rem.

2024-04-27 23:49 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +            sx={{ color: '#a31864', display: 'inline', marginLeft: '5px', marginTop: '-3px' }}
Let's use rem.

2024-04-28 14:14 UTC, mhyneman8 commented
Changed the headings, px's, and updated for mobile.

2024-04-28 14:43 UTC, daleinen7 requested changes
Looks great. Good call on the mobile too. I didn't think to check. 

Just need to adjust the heading levels and I think this is good to go.

2024-04-28 14:43 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +        <h4 mb={1}>
Let's make this an `h3` since the above heading is an `h2`.

2024-04-28 14:43 UTC, daleinen7 commented on client/src/components/RegisterVolunteer/CodeOfConduct.jsx
> +        <h4 my={1}>
Let's make this an `h3`

2024-04-30 16:02 UTC, daleinen7 approved these changes
Looks great. At some point I think we'll want to harmonize the typography across the site, but this looks perfectly good for MVP. 

Nice work.

2024-04-30 16:04 UTC, merged